services:
  backend:
    build: ./backend
    expose:
      - "8001"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SNOWFLAKE_USER=${SNOWFLAKE_USER}
      - SNOWFLAKE_PASSWORD=${SNOWFLAKE_PASSWORD}
      - SNOWFLAKE_ACCOUNT=${SNOWFLAKE_ACCOUNT}
      - SNOWFLAKE_WAREHOUSE=${SNOWFLAKE_WAREHOUSE}
      - SNOWFLAKE_DATABASE=${SNOWFLAKE_DATABASE}
      - SNOWFLAKE_SCHEMA=${SNOWFLAKE_SCHEMA}
      - SNOWFLAKE_ROLE=${SNOWFLAKE_ROLE}
    env_file:
      - .env

  frontend:
    build: ./frontend
    expose:
      - "3000"
    depends_on:
      - backend

  router:
    build:
      context: ./router
    ports:
      - "8000:8000"
    environment:
      - FRONTEND_SERVICE=frontend:3000
      - BACKEND_SERVICE=backend:8001
    depends_on:
      - frontend
      - backend
