version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    env_file:
      - .env

  frontend:
    build: ./frontend/poc-napp
    ports:
      - "3000:3000"
    depends_on:
      - backend
