services:
  backend:
    build: ./backend
    expose:
      - "8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    env_file:
      - .env

  frontend:
    build: ./frontend
    expose:
      - "3000"
    depends_on:
      - backend

  router:
    build:
      context: ./router
      args:
        FRONTEND_SERVICE: frontend:3000
        BACKEND_SERVICE: backend:8000
    ports:
      - "8080:8000"
    environment:
      - FRONTEND_SERVICE=frontend:3000
      - BACKEND_SERVICE=backend:8000
    depends_on:
      - frontend
      - backend
