services:
  backend:
    build: ./backend
    expose:
      - "8001"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    env_file:
      - .env

  frontend:
    build: ./frontend
    expose:
      - "3000"
    depends_on:
      - backend

  router:
    build:
      context: ./router
    ports:
      - "8000:8000"
    environment:
      - FRONTEND_SERVICE=frontend:3000
      - BACKEND_SERVICE=backend:8001
    depends_on:
      - frontend
      - backend
